### ISSUE TITLE
Deploy error for war file bigger  7mb

### ISSUE THREAD

**Issue by CrownID** [tomcatmanager/tomcatmanager#6]
Interrupt throw deploy process for  big war file >7 mb
(remote deploy with curl working the same host)

Ubuntu 14
Python 3.4
remote host: Tomcat 8
Traceback:

> Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1125, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1163, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1121, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 955, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.4/http/client.py", line 917, in send
    self.sock.sendall(data)
ConnectionResetError: [Errno 104] Connection reset by peer

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/somepath/tomcat-manager.py", line 672, in <module>
    sys.exit(main())
  File "/somepath/tomcat-manager.py", line 661, in main
    itm.onecmd(command)
  File "/usr/lib/python3.4/cmd.py", line 217, in onecmd
    return func(arg)
  File "/somepath/tomcat-manager.py", line 486, in do_deploy
    self.docmd(self.__tm.deployWAR, path, fileobj, update, tag)
  File "/somepath/tomcat-manager.py", line 315, in docmd
    return func(*args)
  File "/somepath/depscript/tomcat-manager.py", line 264, in deployWAR
    response = self._execute("deploy", params, wardata, headers, "PUT")
  File "/somepath/tomcat-manager.py", line 160, in _execute
    response = self.__opener.open(req)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

**Comment by kotfu** [comment]
recently switched from url lib to urllib3 and requests. I think that fixed the issue. Verified using a 31mb war file on a tomcat 8.0.32.
