### ISSUE TITLE
requests default timeout

### ISSUE THREAD

**Issue by erentatar** [tomcatmanager/tomcatmanager#95]
When I use start method, I am getting `HTTPConnectionPool(host='idmvtomint1', port=8081): Read timed out. (read timeout=15). ` Can you make it as an optional parameter when initializing TomcatManager instance ? Or can you suggest a proper solution for it ?

Here is the stacktrace:
`Traceback (most recent call last):
  File "C:\virtualenvs\tomcatenv\tmanager.py", line 65, in start
    r = tomcat.start(path, version)
  File "C:\virtualenvs\tomcatenv\lib\site-packages\tomcatmanager\tomcat_manager.py", line 404, in start
    return self._get('start', params)
  File "C:\virtualenvs\tomcatenv\lib\site-packages\tomcatmanager\tomcat_manager.py", line 106, in _get
    r.response = requests.get(
  File "C:\virtualenvs\tomcatenv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\virtualenvs\tomcatenv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\virtualenvs\tomcatenv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\virtualenvs\tomcatenv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\virtualenvs\tomcatenv\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='idmvtomint1', port=8081): Read timed out. (read timeout=15)`

**Comment by kotfu** [comment]
There is a way (undocumented at this point, but I'll fix that shortly) to adjust the timeout.

```
import tomcatmanager as tm
tomcat = tm.TomcatManager()
tomcat.timeout = 20
```
Set `tomcat.timeout` to the number of seconds you want to wait before throwing an exception. If you set it to zero, it will never timeout.

**Comment by kotfu** [comment]
Documentation has been updated at https://tomcatmanager.readthedocs.io/en/develop/api/TomcatManager.html#tomcatmanager.tomcat_manager.TomcatManager.timeout.
